spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: DEC(digicert)

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  server:
    port: 8080

# Logging Configuration
logging:
  file:
    name: logs/reservations.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    com:
      digicert:
        hotel:
          booking: INFO
  pattern:
    rollingPolicy:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    maxHistory: 20

#springdoc:
#  api-docs:
#    enabled: true
#    path: reservations/api-docs
#  swagger-ui:
#      enabled: true
#      path: reservations/swagger-ui.html






